title: CCI25
github_username: grimy86
email: grimy86@proton.me
description: An open-source collection of notes, summaries, insights, etc. on computer science topics into a unified learning resource.
theme: just-the-docs
# plugins:
#  - jekyll-feed
url: https://just-the-docs.github.io
# baseurl: ""

# Mermaid support
mermaid:
  version: "11.6.0"

# Link right of searchbar
aux_links:
  "Original GitHub Repository":
    - "https://github.com/grimy86/CCI25"
aux_links_new_tab: true

# Images
logo: "Images/Logo.png"
# favicon_ico: "Images/Logo.ico"

# Search bar
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

# Anchor tags next to headings
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Callouts
callouts:
  warning:
    title: Warning
    color: red