copyright: >
   <a href="https://github.com/grimy86/grimy86.github.io/blob/main/LICENSE">Copyright &copy; since 2024</a>
site_name: CCI25
site_url: https://grimy86.github.io/
repo_name: grimy86.github.io
repo_url: https://github.com/grimy86/grimy86.github.io
theme:
  name: material
  logo: /Assets/Logo.png
  favicon: /Assets/Logo.png
  language: en

  palette:
# Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: orange

# Intercepted and dispatched via XHR without fully reloading the page
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky, this keept the tabs on the top while scrolling
    - navigation.sections
    # - navigation.expand, this will expand all of the navbar's subsections automatically
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # - content.action.view

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:grimy86@proton.me
    - icon: fontawesome/brands/github 
      link: https://github.com/grimy86

plugins:
  - search

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition # Callouts
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

nav:
  - Home:
    - Home: index.md
    - How to study: study.md

  - Programming:
    - "Getting Started":
        - "Introduction":
            - Workflow: Programming/Foundations/Workflow.md
            - Software and Processes: Programming/Foundations/Software.md
        - "Environment":
            - IDEs and Configs: Programming/Foundations/Configuration.md
            - Memory: Programming/Foundations/Memory.md
        - "Basics":
            - Statements: Programming/Foundations/Statements.md
            - Data Types and Variables: Programming/Foundations/Data_Types.md
            - Entry Point (`main`): Programming/Foundations/Main.md
            - Operators: Programming/Foundations/Operators.md
            - Functions: Programming/Foundations/Functions.md
            - Control flow: Programming/Foundations/Control_Flow.md
            - Preprocessor directives: Programming/Foundations/Preprocessor_Directives.md
    - "Code Design":
        - "Principles":
              - SOLID Principles: Programming/Design/SOLID.md
              - Class Relationships: Programming/Design/Class_Relationships.md
        - "Patterns":
              - Pattern Matching: Programming/Design/Pattern_matching.md
              - Design Patterns: Programming/Design/Design_Patterns.md
        - "Architectures":
              - Common Architectures: Programming/Design/Common_Architectures.md
    - "Assembly":
        - "Architecture":
            - Introduction: Programming/Assembly/Architecture/Introduction.md
            - x86 and x86_64 Architecture: Programming/Assembly/Architecture/x86_Architecture.md
            - Modes of Operation: Programming/Assembly/Architecture/Operating_Modes.md
            - Memory: Programming/Assembly/Architecture/Memory.md
            - CPU Registers: Programming/Assembly/Architecture/CPU_Registers.md
            - E_Flags: Programming/Assembly/Architecture/E_Flags.md
            - Sizes / Words: Programming/Assembly/Architecture/Sizes.md
            - The stack: Programming/Assembly/Architecture/Stack.md
            - Instructions / opcodes: Programming/Assembly/Architecture/Instructions.md
            - Procedures: Programming/Assembly/Architecture/Procedures.md
            - Binary operations: Programming/Assembly/Architecture/Binary_Operations.md
            - Calling Conventions: Programming/Assembly/Architecture/Calling_Conventions.md
        - "Syntax":
            - Reserved words: Programming/Assembly/Syntax/Reserved_Words.md
            - Radix characters: Programming/Assembly/Syntax/Radix_Characters.md
            - Character constants: Programming/Assembly/Syntax/Character_Constants.md
            - Identifiers: Programming/Assembly/Syntax/Identifiers.md
            - Declaring variables: Programming/Assembly/Syntax/Declaring_Variables.md
            - Operator Presedence: Programming/Assembly/Syntax/Operator_Presedence.md
        - "How to compile": Programming/Assembly/Compiling.md
    - "Unmaintained courses":
        - "C#":
            - "Fundamentals":
                - Entry-point, variables, data types & operators: Programming/Resources/CSharp/Level1/Basics.md
                - Control Flow: Programming/Resources/CSharp/Level1/Control_Flow.md
                - Functions & Methods: Programming/Resources/CSharp/Level1/Functions.md
                - Type conversion & parsing: Programming/Resources/CSharp/Level1/Conversion_Parsing.md
                - Data Collections: Programming/Resources/CSharp/Level1/Collections.md
                - Exception handling: Programming/Resources/CSharp/Level1/Exceptions.md
                - Preprocessor directives: Programming/Resources/CSharp/Level1/Preprocessor_Directives.md
                - Object-Oriented Programming (OOP): Programming/Resources/CSharp/Level1/OOP.md
            - "Intermediate concepts":
                - Operator Overloading: Programming/Resources/CSharp/Level2/Operator_Overloading.md
                - Nullable value types: Programming/Resources/CSharp/Level2/Nullable_Types.md
                - Pass by reference: Programming/Resources/CSharp/Level2/Pass_By_Reference.md
                - Generics: Programming/Resources/CSharp/Level2/Generics.md
                - Partial Classes & Partial Methods: Programming/Resources/CSharp/Level2/Partials.md
                - Tuples & Value Tuples: Programming/Resources/CSharp/Level2/Tuples.md
                - Extension Methods: Programming/Resources/CSharp/Level2/Extension_Methods.md
                - Indexers: Programming/Resources/CSharp/Level2/Indexers.md
                - Lambda expressions (Anonymous Functions): Programming/Resources/CSharp/Level2/Lambda.md
                - Delegates, Anonymous Methods, etc.: Programming/Resources/CSharp/Level2/Delegates.md
                - Expression Bodies: Programming/Resources/CSharp/Level2/Expression_Bodies.md
                - Method Hiding: Programming/Resources/CSharp/Level2/Method_Hiding.md
            - "Advanced concepts":
                - Events: Programming/Resources/CSharp/Level3/Events.md
                - Language Integrated Query (LINQ): Programming/Resources/CSharp/Level3/LINQ.md
                - The `IDisposable` interface: Programming/Resources/CSharp/Level3/IDisposable.md
                - Mulithreading & Async: Programming/Resources/CSharp/Level3/Multithread_Async.md
                - Attributes & Reflection: Programming/Resources/CSharp/Level3/Attributes_Reflection.md
            - "Expert concepts":
                - Dependency Injection (DI): Programming/Resources/CSharp/Level4/Dependency_Injection.md
                - Unsafe: Programming/Resources/CSharp/Level4/Unsafe.md
        - "C++":
            - C/C++ Summary: Programming/Resources/Cpp/Cpp.md

  - Windows Internals:
    - "Getting Started":
        - "Introduction":
            - Introduction: Windows_Internals/Introduction.md
            - Terminology: Windows_Internals/Terminology.md
        - ".NET and Libraries":
            - .NET Framework: Windows_Internals/Dotnet_Framework.md
            - Code Libraries: Windows_Internals/Code_Libraries.md
        - "Processes and Execution":
            - Processes, Threads, Fibers, UMS Threads, Handles, Jobs and more: Windows_Internals/Processes.md
            - Processor modes, Privileges, Syscalls, the Kernel and more: Windows_Internals/Processor_Modes.md
        - "Memory Management":
            - Virtual Memory: Windows_Internals/Virtual_Memory.md
        - "Application Interfaces":
            - Introduction to API's: Windows_Internals/API_Introduction.md
            - Windows API, IPC and WinRT: Windows_Internals/Windows_API.md
        - "Executable Formats":
            - Portable Executable file format (PE): Windows_Internals/PE.md

  - About:
      - "About this site":
          - "Meta":
              - Changelog: About/changelog.md
              - Contribution & Style Guide: About/contribute.md
          - "References": About/references.md
          - "Legal": https://github.com/grimy86/grimy86.github.io/blob/main/LICENSE
      - "About me":
          - Portfolio: About/portfolio.md

    
    