copyright: >
   <a href="https://github.com/grimy86/grimy86.github.io/blob/main/LICENSE">Copyright &copy; since 2024</a>
site_name: CCI25
site_url: https://grimy86.github.io/
repo_name: grimy86.github.io
repo_url: https://github.com/grimy86/grimy86.github.io
theme:
  name: material
  logo: /Assets/Logo.png
  favicon: /Assets/Logo.png
  language: en

  palette:
# Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: orange

# Intercepted and dispatched via XHR without fully reloading the page
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky, this keept the tabs on the top while scrolling
    - navigation.sections
    # - navigation.expand, this will expand all of the navbar's subsections automatically
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # - content.action.view

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:grimy86@proton.me
    - icon: fontawesome/brands/github 
      link: https://github.com/grimy86

plugins:
  - search

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition # Callouts
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

nav:
  - Home:
    - Home: index.md
    - How to study: study.md
  - Programming:
    - Introduction: Programming/Foundations/Introduction.md
    - "Phase I-III":
      - "Phase I: Foundations:":
        - Software and Processes: Programming/Foundations/Software.md
        - IDEs and Configs: Programming/Foundations/Configuration.md
        - Memory: Programming/Foundations/Memory.md
        - Statements: Programming/Foundations/Statements.md
        - Data Types, Variables, LValues and RValues.: Programming/Foundations/Data_Types.md
        - Entry Point (`main`): Programming/Foundations/Main.md
  #     - Operators: Programming/P1/Operators.md
  #     - Application Entry-Point & Functions: Programming/P1/Functions.md
  #     - Type Conversion & Parsing: Programming/P1/Conversion.md
  #     - Collections & Arrays: Programming/P1/Collections.md
  #     - Exception Handling: Programming/P1/Exceptions.md
  #     - Preprocessor Directives: Programming/P1/Preprocessor_Directives.md
  #     - Programming Paradigms: Programming/P1/Paradigms.md

#    - "Phase II: Core Competencies": Foo
#
#    - "Phase III: Advanced concepts": Foo

    - "Phase IV: Code Design":
      - Pattern Matching: Programming/Design/Pattern_matching.md
      - SOLID Principles: Programming/Design/SOLID.md
      - Class Relationships: Programming/Design/Class_Relationships.md
      - Design Patterns: Programming/Design/Design_Patterns.md
      - Common Architectures: Programming/Design/Common_Architectures.md

    - "Phase V: Assembly":
      - Architecture:
        - Introduction: Programming/Assembly/Architecture/Introduction.md
        - x86 and x86_64 Architecture: Programming/Assembly/Architecture/x86_Architecture.md
        - Modes of Operation: Programming/Assembly/Architecture/Operating_Modes.md
        - Memory: Programming/Assembly/Architecture/Memory.md
        - CPU Registers: Programming/Assembly/Architecture/CPU_Registers.md
        - E_Flags: Programming/Assembly/Architecture/E_Flags.md
        - Sizes / Words: Programming/Assembly/Architecture/Sizes.md
        - The stack: Programming/Assembly/Architecture/Stack.md
        - Instructions / opcodes: Programming/Assembly/Architecture/Instructions.md
        - Procedures: Programming/Assembly/Architecture/Procedures.md
        - Binary operations: Programming/Assembly/Architecture/Binary_Operations.md
        - Calling Conventions: Programming/Assembly/Architecture/Calling_Conventions.md
      - Syntax:
        - Reserved words: Programming/Assembly/Syntax/Reserved_Words.md
        - Radix characters: Programming/Assembly/Syntax/Radix_Characters.md
        - Character constants: Programming/Assembly/Syntax/Character_Constants.md
        - Identifiers: Programming/Assembly/Syntax/Identifiers.md
        - Declaring variables: Programming/Assembly/Syntax/Declaring_Variables.md
        - Operator Presedence: Programming/Assembly/Syntax/Operator_Presedence.md
      - How to compile: Programming/Assembly/Compiling.md

    - "Legacy / Archived":
      - "C#":
        - Level 1:
          - Entry-point, variables, data types & operators: Programming/Resources/CSharp/Level1/Basics.md
          - Control Flow: Programming/Resources/CSharp/Level1/Control_Flow.md
          - Functions & Methods: Programming/Resources/CSharp/Level1/Functions.md
          - Type conversion & parsing: Programming/Resources/CSharp/Level1/Conversion_Parsing.md
          - Data Collections: Programming/Resources/CSharp/Level1/Collections.md
          - Exception handling: Programming/Resources/CSharp/Level1/Exceptions.md
          - Preprocessor directives: Programming/Resources/CSharp/Level1/Preprocessor_Directives.md
          - Object-Oriented Programming (OOP): Programming/Resources/CSharp/Level1/OOP.md
        - Level 2:
          - Operator Overloading: Programming/Resources/CSharp/Level2/Operator_Overloading.md
          - Nullable value types: Programming/Resources/CSharp/Level2/Nullable_Types.md
          - Pass by reference: Programming/Resources/CSharp/Level2/Pass_By_Reference.md
          - Generics: Programming/Resources/CSharp/Level2/Generics.md
          - Partial Classes & Partial Methods: Programming/Resources/CSharp/Level2/Partials.md
          - Tuples & Value Tuples: Programming/Resources/CSharp/Level2/Tuples.md
          - Extension Methods: Programming/Resources/CSharp/Level2/Extension_Methods.md
          - Indexers: Programming/Resources/CSharp/Level2/Indexers.md
          - Lambda expressions (Anonymous Functions): Programming/Resources/CSharp/Level2/Lambda.md
          - Delegates, Anonymous Methods, etc.: Programming/Resources/CSharp/Level2/Delegates.md
          - Expression Bodies: Programming/Resources/CSharp/Level2/Expression_Bodies.md
          - Method Hiding: Programming/Resources/CSharp/Level2/Method_Hiding.md
        - Level 3:
          - Events: Programming/Resources/CSharp/Level3/Events.md
          - Language Integrated Query (LINQ): Programming/Resources/CSharp/Level3/LINQ.md
          - The `IDisposable` interface: Programming/Resources/CSharp/Level3/IDisposable.md
          - Mulithreading & Async: Programming/Resources/CSharp/Level3/Multithread_Async.md
          - Attributes & Reflection: Programming/Resources/CSharp/Level3/Attributes_Reflection.md
        - Level 4:
          - Dependency Injection (DI): Programming/Resources/CSharp/Level4/Dependency_Injection.md
          - Unsafe: Programming/Resources/CSharp/Level4/Unsafe.md
      - C++:
        - C/C++ Summary: Programming/Resources/Cpp/Cpp.md

  - Windows Internals:
    - Introduction: Windows_Internals/Introduction.md
    - Terminology: Windows_Internals/Terminology.md
    - .NET Framework: Windows_Internals/Dotnet_Framework.md
    - Code Libraries: Windows_Internals/Code_Libraries.md
    - Processes, Threads, Fibers, UMS Threads, Handles, Jobs and more: Windows_Internals/Processes.md
    - Virtual Memory: Windows_Internals/Virtual_Memory.md
    - Introduction to API's: Windows_Internals/API_Introduction.md
    - Windows API, IPC and WinRT: Windows_Internals/Windows_API.md
    - Processor modes, Privileges, Syscalls, the Kernel and more: Windows_Internals/Processor_Modes.md
    - Portable Executable file format (PE): Windows_Internals/PE.md





#  - Reverse Engineering: 
#    - Introduction to analysis: Reverse_Engineering/Intro.md
#    - Static analysis:
#      - Basic: Reverse_Engineering/Basic_static.md
#      - Advanced: Reverse_Engineering/Advanced_static.md
#    - Dynamic analysis:
#      - Basic: Reverse_Engineering/Basic_dynamic.md
#      - Debugging: Reverse_Engineering/Dynamic_debugging.md
#    - Anti-reverse engineering: Reverse_Engineering/Anti_reversing.md
#    - Tool cheat sheets:
#      - CAPA: Reverse_Engineering/CAPA.md
#      - REMnux & FLARE VM: Reverse_Engineering/VMs.md
#
#  - Networks & CyberSecurity:
#    - Networks:
#      - 1. What is a network?: Networks/Networks.md
#      - 2. What are network devices?: Networks/Devices.md
#      - 3. Cisco Packet Tracer Install: Packet_Tracer.md
#    - Cybersecurity:
#      - Pentesting fundamentals: Cybersecurity/General/PentestingFundamentals.md

  - About:
    - Changelog: About/changelog.md
    - Contribution & Style Guide: About/contribute.md
    - About Me: About/github.md
    - Portfolio: About/portfolio.md
    - License: https://github.com/grimy86/grimy86.github.io/blob/main/LICENSE
    - References: About/references.md